### ISSUE TITLE
Replicate the OBIS tools README for PyObisTools

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/pyobistools#29]
R based doc:
https://github.com/iobis/obistools/blob/master/README.md

Build up a similar resource for the pyobistools version of the same tests.

**Comment by ssmosstee** [comment]
Here's my work so far on this: [https://github.com/ssmosstee/pyobistools/blob/main/notebooks_Pyobis_sprint/README.ipynb]

Sorry - had to make a fork because I don't have push or commit permissions on the main project.

**Comment by jeffcullis** [comment]
@ssmosstee I've added you as a maintainer on the pyobistools repo, you should be able to commit and merge in your changes to the doc now.

**Comment by jdpye** [comment]
Included in the main notebook folder now! We will move its output into README.md in a future release
