### ISSUE TITLE
Register dependencies with PyPI

### ISSUE THREAD

**Issue by jdpye** [cioos-siooc/pyobistools#6]
pyobis and xylookup aren't registered with any package index, it would benefit us when using them as dependencies to get them registered into places they can be installed automatically.

**Comment by jdpye** [comment]
triage for the meantime:
```
pip install git+https://github.com/iobis/pyxylookup.git#egg=pyxylookup
pip install git+https://github.com/iobis/obis-qc.git#egg=obisqc
```

**Comment by jdpye** [comment]
I'm eager to see some of these dependencies get a little easier, for example obisqc needs pieterprovoost/isodateparser , and surely for this purpose we don't need to reimagine parsing an ISO 8601 date so thoroughly, but I don't want to request large refactors into other dependencies either.

**Comment by jdpye** [comment]
https://pypi.org/project/python-dateutil/ is the standard date parsing utility for this sort of work

**Comment by jdpye** [comment]
pyworms is in pip and conda already. Since we have implementations or APIs for most of the rest maybe we can get away without importing obis-qc at all.

**Comment by MathewBiddle** [comment]
If this happens, can we get it on conda forge? I'd love to be able to `conda install pyobistools`.

**Comment by jdpye** [comment]
https://pypi.org/project/pyxylookup/ was just added to PyPI! This can move forward now!

**Comment by jdpye** [comment]
Updated the dependency list and made a PR: https://github.com/cioos-siooc/pyobistools/pull/48 

once this is done we should issue a Release from this project, the GH Action that Kyle wrote last year should pick up our PyPI account credentials and publish this module to PyPI.
